#!/bin/sh
set -e
cp -r lib/apps "bin/apps/$1/static/lib"
cp -r bin/stack.io/client/web/stack.io.debug.js "bin/apps/$1/static/stack.io.js"
#cp -r bin/stack.io/client/node/stack.io.js "bin/apps/$1/server/stack.js"